package cn.sunnypuma.buildingtax.application.common.model.base;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("taxdb_admin", "admin_id", Admin.class);
		arp.addMapping("taxdb_building_enterprise", "building_id", BuildingEnterprise.class);
		arp.addMapping("taxdb_building_floor_room", "building_id", BuildingFloorRoom.class);
		arp.addMapping("taxdb_building_info", "building_id", BuildingInfo.class);
		arp.addMapping("taxdb_building_info_extend", "id", BuildingInfoExtend.class);
		arp.addMapping("taxdb_enterprise_info", "enterprise_id", EnterpriseInfo.class);
		arp.addMapping("taxdb_enterprise_info_extend", "id", EnterpriseInfoExtend.class);
		arp.addMapping("taxdb_enterprise_position", "enterprise_id", EnterprisePosition.class);
		arp.addMapping("taxdb_floor_info", "floor_id", FloorInfo.class);
		arp.addMapping("taxdb_permission_info", "permission_id", PermissionInfo.class);
		arp.addMapping("taxdb_position_info", "position_id", PositionInfo.class);
		arp.addMapping("taxdb_role_info", "role_id", RoleInfo.class);
		// Composite Primary Key order: permission_id,role_id
		arp.addMapping("taxdb_role_permission", "permission_id,role_id", RolePermission.class);
		arp.addMapping("taxdb_room_info", "room_id", RoomInfo.class);
		arp.addMapping("taxdb_room_info_extend", "id", RoomInfoExtend.class);
		arp.addMapping("taxdb_user_enterprise", "user_id", UserEnterprise.class);
		arp.addMapping("taxdb_user_info", "user_id", UserInfo.class);
		arp.addMapping("taxdb_user_info_extend", "id", UserInfoExtend.class);
		arp.addMapping("taxdb_user_lock_list", "lock_ip", UserLockList.class);
		arp.addMapping("taxdb_user_login_log", "user_id", UserLoginLog.class);
		arp.addMapping("taxdb_user_role", "user_id", UserRole.class);
	}
}

