package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
}
