package cn.sunnypuma.buildingtax.application.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEnterpriseInfo<M extends BaseEnterpriseInfo<M>> extends Model<M> implements IBean {

	public M setEnterpriseId(java.lang.String enterpriseId) {
		set("enterprise_id", enterpriseId);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseId() {
		return getStr("enterprise_id");
	}

	public M setEnterpriseName(java.lang.String enterpriseName) {
		set("enterprise_name", enterpriseName);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseName() {
		return getStr("enterprise_name");
	}

	public M setEnterpriseProperty(java.lang.String enterpriseProperty) {
		set("enterprise_property", enterpriseProperty);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseProperty() {
		return getStr("enterprise_property");
	}

	public M setEnterpriseScale(java.lang.String enterpriseScale) {
		set("enterprise_scale", enterpriseScale);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseScale() {
		return getStr("enterprise_scale");
	}

	public M setHomepage(java.lang.String homepage) {
		set("homepage", homepage);
		return (M)this;
	}
	
	public java.lang.String getHomepage() {
		return getStr("homepage");
	}

	public M setEnterpriseAvatar(java.lang.String enterpriseAvatar) {
		set("enterprise_avatar", enterpriseAvatar);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseAvatar() {
		return getStr("enterprise_avatar");
	}

	public M setEstablishmentTime(java.util.Date establishmentTime) {
		set("establishment_time", establishmentTime);
		return (M)this;
	}
	
	public java.util.Date getEstablishmentTime() {
		return get("establishment_time");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setEnterpriseBref(java.lang.String enterpriseBref) {
		set("enterprise_bref", enterpriseBref);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseBref() {
		return getStr("enterprise_bref");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setExtendField(java.lang.String extendField) {
		set("extend_field", extendField);
		return (M)this;
	}
	
	public java.lang.String getExtendField() {
		return getStr("extend_field");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
