package cn.sunnypuma.buildingtax.application.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public M setAdminId(java.lang.String adminId) {
		set("admin_id", adminId);
		return (M)this;
	}
	
	public java.lang.String getAdminId() {
		return getStr("admin_id");
	}

	public M setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	public M setHeslo(java.lang.String heslo) {
		set("heslo", heslo);
		return (M)this;
	}
	
	public java.lang.String getHeslo() {
		return getStr("heslo");
	}

	public M setAdminTel(java.lang.String adminTel) {
		set("admin_tel", adminTel);
		return (M)this;
	}
	
	public java.lang.String getAdminTel() {
		return getStr("admin_tel");
	}

	public M setAdminEmail(java.lang.String adminEmail) {
		set("admin_email", adminEmail);
		return (M)this;
	}
	
	public java.lang.String getAdminEmail() {
		return getStr("admin_email");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public M setExtendField(java.lang.String extendField) {
		set("extend_field", extendField);
		return (M)this;
	}
	
	public java.lang.String getExtendField() {
		return getStr("extend_field");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}
	
	public M setAdminDetail(java.lang.String adminDetail) {
		set("admin_detail", adminDetail);
		return (M)this;
	}
	
	public java.lang.String getAdminDetail() {
		return getStr("admin_detail");
	}


}
