package cn.sunnypuma.buildingtax.application.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuildingInfo<M extends BaseBuildingInfo<M>> extends Model<M> implements IBean {

	public M setBuildingId(java.lang.String buildingId) {
		set("building_id", buildingId);
		return (M)this;
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_id");
	}

	public M setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
		return (M)this;
	}
	
	public java.lang.String getBuildingName() {
		return getStr("building_name");
	}

	public M setBuildingPosition(java.lang.String buildingPosition) {
		set("building_position", buildingPosition);
		return (M)this;
	}
	
	public java.lang.String getBuildingPosition() {
		return getStr("building_position");
	}

	public M setBuildingDirection(java.lang.String buildingDirection) {
		set("building_direction", buildingDirection);
		return (M)this;
	}
	
	public java.lang.String getBuildingDirection() {
		return getStr("building_direction");
	}

	public M setBuildingDate(java.util.Date buildingDate) {
		set("building_date", buildingDate);
		return (M)this;
	}
	
	public java.util.Date getBuildingDate() {
		return get("building_date");
	}

	public M setFloorArea(java.lang.String floorArea) {
		set("floor_area", floorArea);
		return (M)this;
	}
	
	public java.lang.String getFloorArea() {
		return getStr("floor_area");
	}

	public M setFloor(java.lang.String floor) {
		set("floor", floor);
		return (M)this;
	}
	
	public java.lang.String getFloor() {
		return getStr("floor");
	}

	public M setBuildingBref(java.lang.String buildingBref) {
		set("building_bref", buildingBref);
		return (M)this;
	}
	
	public java.lang.String getBuildingBref() {
		return getStr("building_bref");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setExtendField(java.lang.String extendField) {
		set("extend_field", extendField);
		return (M)this;
	}
	
	public java.lang.String getExtendField() {
		return getStr("extend_field");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setAdded1(java.lang.String added1) {
		set("added1", added1);
		return (M)this;
	}
	
	public java.lang.String getAdded1() {
		return getStr("added1");
	}

}
