package cn.sunnypuma.buildingtax.application.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoomInfo<M extends BaseRoomInfo<M>> extends Model<M> implements IBean {

	public M setRoomId(java.lang.String roomId) {
		set("room_id", roomId);
		return (M)this;
	}
	
	public java.lang.String getRoomId() {
		return getStr("room_id");
	}

	public M setRoomNum(java.lang.String roomNum) {
		set("room_num", roomNum);
		return (M)this;
	}
	
	public java.lang.String getRoomNum() {
		return getStr("room_num");
	}

	public M setRoomBuilding(java.lang.String roomBuilding) {
		set("room_building", roomBuilding);
		return (M)this;
	}
	
	public java.lang.String getRoomBuilding() {
		return getStr("room_building");
	}

	public M setRoomUnit(java.lang.String roomUnit) {
		set("room_unit", roomUnit);
		return (M)this;
	}
	
	public java.lang.String getRoomUnit() {
		return getStr("room_unit");
	}

	public M setRoomFloor(java.lang.String roomFloor) {
		set("room_floor", roomFloor);
		return (M)this;
	}
	
	public java.lang.String getRoomFloor() {
		return getStr("room_floor");
	}

	public M setRoomArea(java.lang.Float roomArea) {
		set("room_area", roomArea);
		return (M)this;
	}
	
	public java.lang.Float getRoomArea() {
		return getFloat("room_area");
	}

	public M setRoomPictures(java.lang.String roomPictures) {
		set("room_pictures", roomPictures);
		return (M)this;
	}
	
	public java.lang.String getRoomPictures() {
		return getStr("room_pictures");
	}

	public M setRoomHost(java.lang.String roomHost) {
		set("room_host", roomHost);
		return (M)this;
	}
	
	public java.lang.String getRoomHost() {
		return getStr("room_host");
	}

	public M setIsusing(java.lang.String isusing) {
		set("isusing", isusing);
		return (M)this;
	}
	
	public java.lang.String getIsusing() {
		return getStr("isusing");
	}

	public M setRoomType(java.lang.String roomType) {
		set("room_type", roomType);
		return (M)this;
	}
	
	public java.lang.String getRoomType() {
		return getStr("room_type");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public M setRoomDirection(java.lang.String roomDirection) {
		set("room_direction", roomDirection);
		return (M)this;
	}
	
	public java.lang.String getRoomDirection() {
		return getStr("room_direction");
	}

	public M setExtendField(java.lang.String extendField) {
		set("extend_field", extendField);
		return (M)this;
	}
	
	public java.lang.String getExtendField() {
		return getStr("extend_field");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
