package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseBuildingInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuildingInfo extends BaseBuildingInfo<BuildingInfo> {
	public static final BuildingInfo dao = new BuildingInfo().dao();
}
