package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseBuildingInfoExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuildingInfoExtend extends BaseBuildingInfoExtend<BuildingInfoExtend> {
	public static final BuildingInfoExtend dao = new BuildingInfoExtend().dao();
}
