package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseBuildingEnterprise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuildingEnterprise extends BaseBuildingEnterprise<BuildingEnterprise> {
	public static final BuildingEnterprise dao = new BuildingEnterprise().dao();
}
