package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseBuildingFloorRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuildingFloorRoom extends BaseBuildingFloorRoom<BuildingFloorRoom> {
	public static final BuildingFloorRoom dao = new BuildingFloorRoom().dao();
}
