package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseEnterpriseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnterpriseInfo extends BaseEnterpriseInfo<EnterpriseInfo> {
	public static final EnterpriseInfo dao = new EnterpriseInfo().dao();
}
