package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseEnterpriseInfoExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnterpriseInfoExtend extends BaseEnterpriseInfoExtend<EnterpriseInfoExtend> {
	public static final EnterpriseInfoExtend dao = new EnterpriseInfoExtend().dao();
}
