package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseEnterprisePosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnterprisePosition extends BaseEnterprisePosition<EnterprisePosition> {
	public static final EnterprisePosition dao = new EnterprisePosition().dao();
}
