package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseFloorInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FloorInfo extends BaseFloorInfo<FloorInfo> {
	public static final FloorInfo dao = new FloorInfo().dao();
}
