package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BasePermissionInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionInfo extends BasePermissionInfo<PermissionInfo> {
	public static final PermissionInfo dao = new PermissionInfo().dao();
}
