package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BasePositionInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PositionInfo extends BasePositionInfo<PositionInfo> {
	public static final PositionInfo dao = new PositionInfo().dao();
}
