package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseRoleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleInfo extends BaseRoleInfo<RoleInfo> {
	public static final RoleInfo dao = new RoleInfo().dao();
}
