package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseRoomInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomInfo extends BaseRoomInfo<RoomInfo> {
	public static final RoomInfo dao = new RoomInfo().dao();
}
