package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseRoomInfoExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomInfoExtend extends BaseRoomInfoExtend<RoomInfoExtend> {
	public static final RoomInfoExtend dao = new RoomInfoExtend().dao();
}
