package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseUserLockList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLockList extends BaseUserLockList<UserLockList> {
	public static final UserLockList dao = new UserLockList().dao();
}
