package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseUserLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLoginLog extends BaseUserLoginLog<UserLoginLog> {
	public static final UserLoginLog dao = new UserLoginLog().dao();
}
