package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
	public static final UserInfo dao = new UserInfo().dao();
}
