package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseUserEnterprise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserEnterprise extends BaseUserEnterprise<UserEnterprise> {
	public static final UserEnterprise dao = new UserEnterprise().dao();
}
