package cn.sunnypuma.buildingtax.application.common.model.base;

import cn.sunnypuma.buildingtax.application.common.model.base.BaseUserInfoExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfoExtend extends BaseUserInfoExtend<UserInfoExtend> {
	public static final UserInfoExtend dao = new UserInfoExtend().dao();
}
